version: 2

jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run: shellcheck --version
      - run: shellcheck --exclude=SC2039 *.sh

  test:
    docker:
      - image: kakakakakku/amazonlinux-bats
    steps:
      - checkout
      - run: bats *.bats

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - test
